url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Qiming Cao" # the name of your site, e.g. ACME Corp.
description: "PhD Student at Purdue University"
email: "cao393@purdue.edu"